name: build X64
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v6

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Enable GitHub Actions cache for vcpkg
      uses: actions/github-script@v9
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Build
      shell: pwsh
      run: |
        $env:VERSION_BUILD_NUMBER = "${{github.run_number}}"
        .\build-ci.ps1

    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: wiliwili-uwp-X64
        path: |
          build\AppPackages\wiliwili-uwp\*\*.msixbundle
          build\AppPackages\wiliwili-uwp\*\*.msix
          build\AppPackages\wiliwili-uwp\*\*.appx
          build\AppPackages\wiliwili-uwp\*\*.cer
          build\AppPackages\wiliwili-uwp\*\Dependencies\x64\*
