name: build X64
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      shell: pwsh
      run: |
        $env:VERSION_BUILD_NUMBER = "${{github.run_number}}"
        .\build-ci.ps1

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wiliwili-uwp-X64
        path: |
          build\AppPackages\wiliwili-uwp\*\*.msixbundle
          build\AppPackages\wiliwili-uwp\*\*.msix
          build\AppPackages\wiliwili-uwp\*\*.appx
          build\AppPackages\wiliwili-uwp\*\*.cer
          build\AppPackages\wiliwili-uwp\*\Dependencies\x64\*
